! FRRouting Configuration for Route Reflector 1
!
log stdio
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
exit
!
interface eth0
 ip address 10.1.1.1/30
 ip ospf area 0
exit
!
interface eth1
 ip address 10.1.1.5/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.1.1.9/30
 ip ospf area 0
exit
!
router ospf
exit
!
router bgp 1
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 neighbor LEAFS peer-group
 neighbor LEAFS remote-as 1
 neighbor LEAFS update-source lo
 bgp listen range 1.1.1.0/24 peer-group LEAFS
 !
 address-family l2vpn evpn
  neighbor LEAFS activate
  neighbor LEAFS route-reflector-client
 exit-address-family
exit
!
